# Generated by Django 2.2.5 on 2019-11-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yevrus', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MultipleChoice',
            new_name='Choice',
        ),
        migrations.DeleteModel(
            name='CheckboxChoice',
        ),
    ]
