# Generated by Django 2.2.5 on 2019-11-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yevrus', '0002_auto_20191117_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='submit_date',
            field=models.DateTimeField(default='2019-01-01 06:00:00.000000-08:00'),
            preserve_default=False,
        ),
    ]
