# Generated by Django 2.2.5 on 2019-11-18 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yevrus', '0003_response_submit_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='username',
            new_name='user',
        ),
    ]
