# Generated by Django 2.2.5 on 2019-11-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yevrus', '0005_survey_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='is_done',
            field=models.BooleanField(),
        ),
    ]
