# Generated by Django 2.2.5 on 2019-11-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yevrus', '0006_auto_20191119_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
