# Generated by Django 2.2.5 on 2019-11-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yevrus', '0008_auto_20191124_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='publish_date',
            field=models.DateTimeField(null=True),
        ),
    ]
